# Base configs
baseurl: "https://yodin23.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-136081898-1"

# UI configs
title: "Photography by Maxime Fraval"
subtitle: "See the world through my eyes!"
author: "Maxime Fraval"
header:
 title: "Photography"
 subtitle: "by Maxime Fraval"
footer:
 name: "Hey there, my name is Maxime"
 bio: "I am a engineer from France, I like photography, food and travel."
 github: "<a href=\"https://yodin23.github.io/photography/"> ;)"
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
